// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBMSSearchInfoByMD5(arg1) {
  return window['go']['app']['BMSSearchHandler']['GetBMSSearchInfoByMD5'](arg1);
}

export function LookupBMSSearchByMD5(arg1) {
  return window['go']['app']['BMSSearchHandler']['LookupBMSSearchByMD5'](arg1);
}

export function SetContext(arg1) {
  return window['go']['app']['BMSSearchHandler']['SetContext'](arg1);
}

export function UnlinkBMSSearchByFolder(arg1) {
  return window['go']['app']['BMSSearchHandler']['UnlinkBMSSearchByFolder'](arg1);
}

export function UnlinkBMSSearchByMD5(arg1) {
  return window['go']['app']['BMSSearchHandler']['UnlinkBMSSearchByMD5'](arg1);
}
