// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function GetBMSSearchInfoByMD5(arg1:string):Promise<dto.BMSSearchInfoDTO>;

export function LookupBMSSearchByMD5(arg1:string):Promise<dto.BMSSearchInfoDTO>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UnlinkBMSSearchByFolder(arg1:string):Promise<void>;

export function UnlinkBMSSearchByMD5(arg1:string):Promise<void>;
