// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function GetChartDetailByMD5(arg1:string):Promise<dto.ChartDTO>;

export function GetChartMetaByMD5(arg1:string):Promise<dto.ChartIRMetaDTO>;

export function ListCharts():Promise<Array<dto.ChartListItemDTO>>;

export function SetContext(arg1:context.Context):Promise<void>;
