// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteChartFile(arg1) {
  return window['go']['app']['ChartHandler']['DeleteChartFile'](arg1);
}

export function GetChartDetailByMD5(arg1, arg2) {
  return window['go']['app']['ChartHandler']['GetChartDetailByMD5'](arg1, arg2);
}

export function GetChartMetaByMD5(arg1) {
  return window['go']['app']['ChartHandler']['GetChartMetaByMD5'](arg1);
}

export function ListChartPathsByMD5(arg1) {
  return window['go']['app']['ChartHandler']['ListChartPathsByMD5'](arg1);
}

export function ListCharts() {
  return window['go']['app']['ChartHandler']['ListCharts']();
}

export function SetContext(arg1) {
  return window['go']['app']['ChartHandler']['SetContext'](arg1);
}
