// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteImport(arg1) {
  return window['go']['app']['DiffImportHandler']['ExecuteImport'](arg1);
}

export function IsEstimateRunning() {
  return window['go']['app']['DiffImportHandler']['IsEstimateRunning']();
}

export function ParseAndEstimate(arg1) {
  return window['go']['app']['DiffImportHandler']['ParseAndEstimate'](arg1);
}

export function StopEstimate() {
  return window['go']['app']['DiffImportHandler']['StopEstimate']();
}
