// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function AddDifficultyTable(arg1:string):Promise<void>;

export function EstimateInstallLocation(arg1:string,arg2:number):Promise<Array<dto.InstallCandidateDTO>>;

export function GetDifficultyTableEntry(arg1:number,arg2:string):Promise<dto.DifficultyTableEntryDTO>;

export function ListDifficultyTableEntries(arg1:number):Promise<Array<dto.DifficultyTableEntryDTO>>;

export function ListDifficultyTables():Promise<Array<dto.DifficultyTableDTO>>;

export function RefreshAllDifficultyTables():Promise<Array<dto.DifficultyTableRefreshResult>>;

export function RefreshDifficultyTable(arg1:number):Promise<dto.DifficultyTableRefreshResult>;

export function RemoveDifficultyTable(arg1:number):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
