// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ExecuteImport(arg1:app.DiffImportCandidateDTO[]):Promise<app.DiffImportResultDTO>;

export function IsEstimateRunning():Promise<boolean>;

export function ParseAndEstimate(arg1:string[]):Promise<app.DiffImportCandidateDTO[]>;

export function StopEstimate():Promise<void>;
