// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDifficultyTable(arg1) {
  return window['go']['app']['DifficultyTableHandler']['AddDifficultyTable'](arg1);
}

export function EstimateInstallLocation(arg1, arg2) {
  return window['go']['app']['DifficultyTableHandler']['EstimateInstallLocation'](arg1, arg2);
}

export function GetDifficultyTableEntry(arg1, arg2) {
  return window['go']['app']['DifficultyTableHandler']['GetDifficultyTableEntry'](arg1, arg2);
}

export function ListDifficultyTableEntries(arg1) {
  return window['go']['app']['DifficultyTableHandler']['ListDifficultyTableEntries'](arg1);
}

export function ListDifficultyTables() {
  return window['go']['app']['DifficultyTableHandler']['ListDifficultyTables']();
}

export function RefreshAllDifficultyTables() {
  return window['go']['app']['DifficultyTableHandler']['RefreshAllDifficultyTables']();
}

export function RefreshDifficultyTable(arg1) {
  return window['go']['app']['DifficultyTableHandler']['RefreshDifficultyTable'](arg1);
}

export function RemoveDifficultyTable(arg1) {
  return window['go']['app']['DifficultyTableHandler']['RemoveDifficultyTable'](arg1);
}

export function SetContext(arg1) {
  return window['go']['app']['DifficultyTableHandler']['SetContext'](arg1);
}
