// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function ExecuteImport(arg1:Array<app.DiffImportCandidateDTO>):Promise<app.DiffImportResultDTO>;

export function IsEstimateRunning():Promise<boolean>;

export function ParseAndEstimate(arg1:Array<string>):Promise<Array<app.DiffImportCandidateDTO>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StopEstimate():Promise<void>;
