// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function IsSyncing():Promise<boolean>;

export function ListEvents():Promise<Array<dto.EventDTO>>;

export function RefreshEventsFromBMSSearch():Promise<number>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartBMSSearchSync():Promise<void>;

export function StopBMSSearchSync():Promise<void>;

export function UpdateEventShortName(arg1:number,arg2:string):Promise<void>;
