// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsSyncing() {
  return window['go']['app']['EventHandler']['IsSyncing']();
}

export function ListEvents() {
  return window['go']['app']['EventHandler']['ListEvents']();
}

export function RefreshEventsFromBMSSearch() {
  return window['go']['app']['EventHandler']['RefreshEventsFromBMSSearch']();
}

export function SetContext(arg1) {
  return window['go']['app']['EventHandler']['SetContext'](arg1);
}

export function StartBMSSearchSync() {
  return window['go']['app']['EventHandler']['StartBMSSearchSync']();
}

export function StopBMSSearchSync() {
  return window['go']['app']['EventHandler']['StopBMSSearchSync']();
}

export function UpdateEventReleaseYear(arg1, arg2) {
  return window['go']['app']['EventHandler']['UpdateEventReleaseYear'](arg1, arg2);
}

export function UpdateEventShortName(arg1, arg2) {
  return window['go']['app']['EventHandler']['UpdateEventShortName'](arg1, arg2);
}
