// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {similarity} from '../models';

export function GetConfig():Promise<main.Config>;

export function Init():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function ScanDuplicates():Promise<Array<similarity.DuplicateGroup>>;

export function SelectFile():Promise<string>;
